name: Test Plan

on:

  push:

    branches:

      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install dependencies

        run: npm install

      - name: Run test plan

        run: npm test

      - name: Commit test results

        uses: EndBug/add-and-commit@v7

        with:

          author_name: Your Name

          author_email: your-email@example.com

          message: Add test results

          add: |

            test-results/*

          signoff: true

